move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["point1"] #, "point2", "point3", "point4", "point5", "point6"]
    waypoint_coords:
      point1: [1.0, 0.0, 1.570796327]
      #point1: [2.5, -6.2, 1.570796327]
      #point2: [1.0, 0.0, 0.0]
      #point3: [1.5, 0.0, 0.0]
      #point4: [2.0, 0.0, 0.0]
      #point5: [2.5, 0.0, 0.0]
      #point6: [3.0, 0.0, 0.0]

recharge:
  ros__parameters:
    plugins:
      - plansys2_recharge_bt_node

photo:
  ros__parameters:
    plugins:
      - rover_photo_bt_node

record:
  ros__parameters:
    plugins:
      - rover_record_bt_node

calibration:
  ros__parameters:
    plugins:
      - rover_calibration_bt_node
