move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["point1", "point2", "point3"]
    waypoint_coords:
      point1: [8.0, 1.0, 0.0]
      point2: [15.0, 10.0, 0.0]
      point3: [9.0, 13.0, 0.0]


recharge:
  ros__parameters:
    plugins:
      - plansys2_recharge_bt_node

photo:
  ros__parameters:
    plugins:
      - rover_photo_bt_node

record:
  ros__parameters:
    plugins:
      - rover_record_bt_node

calibration:
  ros__parameters:
    plugins:
      - rover_calibration_bt_node
