move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["point1", "point2", "point3", "point4", "point5"]
    waypoint_coords:
      point1: [0.0, -3.0, 0.785398163]
      point2: [4.0, -4.025, 0.0]
      point3: [-9.0, -5.5, 3.1415]
      point4: [-21.0, 0.0, 0.785398163]
      point5: [0.0, 8.0, -0.78]

recharge:
  ros__parameters:
    plugins:
      - plansys2_recharge_bt_node

photo:
  ros__parameters:
    plugins:
      - rover_photo_bt_node

record:
  ros__parameters:
    plugins:
      - rover_record_bt_node

calibration:
  ros__parameters:
    plugins:
      - rover_calibration_bt_node
