move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["punto1", "punto2", "punto3", "punto4", "punto5", "punto6"]
    waypoint_coords:
      punto1: [0.0, -3.0, 0.0]
      punto2: [4.0, -4.025, 0.0]
      punto3: [-10.0, -5.5, 0.0]
      punto4: [21.0, 0.0, 0.785398163]
      punto5: [0.0, 8.0, 0.0]
      punto6: [11.0, 13.0, -2.094395102]

recharge:
  ros__parameters:
    plugins:
      - plansys2_recharge_bt_node

photo:
  ros__parameters:
    plugins:
      - rover_photo_bt_node

record:
  ros__parameters:
    plugins:
      - rover_record_bt_node

calibration:
  ros__parameters:
    plugins:
      - rover_calibration_bt_node
